services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: devops-lab-service-compose
    ports:
      - "8000:8000"

  prometheus:
    image: prom/prometheus:latest
    container_name: devops-lab-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ../monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - app

  grafana:
    image: grafana/grafana:latest
    container_name: devops-lab-grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
